apiVersion: batch/v1
kind: CronJob
metadata:
  name: {{ required "Missing .Values.name" .Values.name }}
  namespace: {{ required "Missing .Values.namespace" .Values.namespace }}
spec:
  {{- if not .Values.schedule }}
  schedule: {{ required "Missing .Values.schedule" .Values.schedule }}
  {{- else if kindIs "float64" .Values.schedule }}
  schedule: {{ .Values.schedule }}
  {{- else if kindIs "map" .Values.schedule }}
  {{- if eq .Values.environment "dev" }}
  schedule: {{ required "Missing .Values.schedule.dev" .Values.schedule.dev }}
  {{- else if eq .Values.environment "test" }}
  schedule: {{ required "Missing .Values.schedule.test" .Values.schedule.test }}
  {{- else if eq .Values.environment "prod" }}
  schedule: {{ required "Missing .Values.schedule.prod" .Values.schedule.prod }}
  {{- end }}
  {{- else }}
  {{- fail ".Values.replicaCount must either be a number or a map" }}
  {{- end }}

  jobTemplate:
    spec:
      backoffLimit: 0
      template:
        spec:
          securityContext:
            fsGroup: 1001
            supplementalGroups:
            - 1001
          containers:
          - name: {{ required "Missing .Values.name" .Values.name }}
            image: {{ include "image" . }} 
            imagePullPolicy: Always
            env:
            - name: ENVIRONMENT
              value: {{ required "Missing .Values.environment" $.Values.environment }}
            - name: pythonpath
              value: {{ required "Missing .Values.pythonpath" $.Values.pythonpath }}
            {{- with .Values.command }}
            args:
              {{- toYaml . | nindent 12 }}
            {{- end }}
            securityContext:
              allowPrivilegeEscalation: false
              runAsGroup: 1001
              runAsUser: 1001
              seccompProfile:
                type: RuntimeDefault
            resources:
              limits:
                cpu: 800m
                memory: 1Gi
              requests:
                cpu: 50m
                memory: 100Mi
          restartPolicy: Never
          serviceAccount: {{ required "Missing .Values.serviceAccount" $.Values.serviceAccount }}
          serviceAccountName: {{ required "Missing .Values.serviceAccount" $.Values.serviceAccount }}
  successfulJobsHistoryLimit: 0
  failedJobsHistoryLimit: 1